kiali-operator:
  clusterRoleCreator: true
  cr:
    create: true
    name: kiali
    namespace: istio-system
    spec:
      api:
        namespaces:
          exclude:
          - istio-operator
          - kube-.*
          - kiali-operator
          - monitoring
      auth:
        strategy: token
      deployment:
        accessible_namespaces:
        - '**'
        image_name: quay.io/kiali/kiali
        image_version: v1.43.0
        ingress:
          enabled: true
          override_yaml:
            metadata:
              annotations:
                alb.ingress.kubernetes.io/group.name: internal-tools
                alb.ingress.kubernetes.io/scheme: internal
                alb.ingress.kubernetes.io/subnets: subnet-A,subnet-B
                alb.ingress.kubernetes.io/tags: Project Name=Xebia
                kubernetes.io/ingress.class: alb
            spec:
              rules:
              - host: kiali.example.com
                http:
                  paths:
                  - backend:
                      service:
                        name: kiali
                        port:
                          number: 20001
                    path: /kiali
                    pathType: Prefix
        instance_name: kiali
        namespace: istio-system
        replicas: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
        service_type: NodePort
        view_only_mode: false
      version: default
  env:
  - name: ALLOW_AD_HOC_KIALI_IMAGE
    value: "true"
  image:
    repo: quay.io/kiali/kiali-operator
    tag: v1.43.0
  metrics:
    enabled: true
  onlyViewOnlyMode: false
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi
  watchNamespace: ""
