---
- name: Example Playbook
  hosts: all
  tasks:
    - name: Create directory if it doesn't exist
      ansible.builtin.file:
        path: "/home/ubuntu/{{ dir_name }}"
        state: directory
      register: dir_result

    - name: Check if local file exists
      local_action: stat path=./pipeline.txt
      register: local_file

    - name: Copy file from local to remote
      ansible.builtin.copy:
        src: ./pipeline.txt
        dest: /home/ubuntu/pipeline.txt
      when: local_file.stat.exists

    - name: Create result.txt file with specific content
      ansible.builtin.copy:
        dest: "/home/ubuntu/{{ dir_name }}/result.txt"
        content: "This file is created by xlr8s."