# Default values for jaeger-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ingress:
  enabled: true
  namespace: istio-system
  annotations:
    #alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:147642600964:certificate/fcb6561c-2079-4967-8239-37405e53dc58
    alb.ingress.kubernetes.io/group.name: internal-tools
    #alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-A,subnet-B
    alb.ingress.kubernetes.io/tags: Project Name=Xebia
    kubernetes.io/ingress.class: alb
  rules:
  - host: jaeger.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jaeger-jaeger-operator-jaeger-query
            port:
              number: 16686


jaeger-operator: 
  image:
    repository: jaegertracing/jaeger-operator
    tag: 1.28.0
  crd:
    install: true
  rbac:
    create: true
    clusterRole: true

  resources: 
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 128Mi

  jaeger:
    # Specifies whether Jaeger instance should be created
    create: true
    # namespace where Jaeger resource should be created default to .Release.Namespace
    namespace: istio-system
    spec: 
    ## Production Confuguration
      #strategy: production
      # storage:
      #   type: elasticsearch
      #     elasticsearch:
      #     nodeCount: 3
      #     resources:
      #       requests:
      #         cpu: 200m
      #         memory: 1Gi
      #       limits:
      #         memory: 1Gi
      
    ## Production Configuration but external elasticsearch 
      #strategy: production
      # storage:
      #   type: elasticsearch
      #   options:
      #     es:
      #       server-urls: http://elasticsearch.default.svc:9200
          
    ## Dev/Test environment configuration
      strategy: allInOne
      allInOne:
        image: jaegertracing/all-in-one:1.13
        #options:
        #  log-level: debug
      storage:
        options:
          memory:
            max-traces: 100000
      query:
        serviceType: NodePort
      ingress:
         enabled: false