apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Values.name}}
spec:
  profile: {{.Values.profile}}
  hub: {{.Values.hub}}
  tag: {{.Values.tag}}
  values:
    gateways:
      istio-ingressgateway:
        type: {{.Values.gateways.istioIngressgateway.type}}
