apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
git:
  repoUrl: git@github.com:xi2424-npanjwani/xlr8s-demo.git
  revision: main
modules:
  terraform:
  - module: git@github.com:xebiaww-apps/terraform-aws-xebia-vpc.git
    ref:
      tag: v0.10.0
name: xlr8s-demo-9723
vars:
  apps: null
  policy: null
