apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
git:
  repoUrl: git@github.com:xi2424-npanjwani/xlr8s-demo.git
  revision: main
name: xlr8s-demo-9723
vars:
  apps: null
  policy: null
