apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: "gatekeeper-system"
spec:
  sync:
    syncOnly:
      - group: "autoscaling"
        version: "v2beta2"
        kind: "HorizontalPodAutoscaler"

